# Generated by Django 5.0.6 on 2024-06-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_contact_us_amount_alter_contact_us_phone_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_us',
            name='property',
            field=models.CharField(choices=[('industrial', 'industrial'), ('commercial', 'commercial'), ('residential', 'residential')], max_length=20),
        ),
    ]
