# Generated by Django 5.0.6 on 2024-06-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_contact_us_property'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_us',
            name='property',
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='amount',
            field=models.TextField(blank=True, max_length=19, null=True),
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='phone_no',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
